[package]
name = "ark-tagger"
version = "0.1.0"
authors = ["Kirill Taran <kirill.t256@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
crc32fast = "1.2.0"
